title:            //Saurabh Shrivastava
description:      " May The Twenty Fourth Be With You "
logo:             saurabh_logo_s.png
disqus_shortname: saurabhshri
share:            true
dropcap:		    	true
# Change url to your domain. Leave localhost server or blank when working locally.
# or use the hint from http://jekyllrb.com/docs/github-pages/ to keep this the same 
# whether working locally or remotely. Start Jekyll with: jekyll serve --baseurl ''

url:        	  https://saurabhshri.github.io

# Owner/author information
owner:
  name:           Saurabh Shrivastava
  avatar:         saurabh_shrivastava_logo_circle.png
  email:          saurabh.shrivastava54@gmail.com
  # Use the coder's toolbox at http://coderstoolbox.net/string/#!encoding=xml&action=encode&charset=us_ascii to encode your description into XML string
  description:    Student | Learner | Creator
  # Social networking links used in footer. Update and remove as you like.
  twitter:        shubh_saurabh
  #facebook:       
  github:         saurabhshri      
  #instagram:      
  # For Google Authorship https://plus.google.com/authorship
  google_plus:    https://plus.google.com/u/0/+saurabhshrivastava24

# Analytics and webmaster tools stuff goes here

google_analytics:   UA-93488639-1
google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:         

# Links to include in footer navigation
# For external links add external: true
links:
  - title: Home
    url: /
    external: false
    icon: home
  - title: Featured Posts
    url: /featured
  - title: Categories
    url: /categories
  - title: GSoC
    url: /gsoc
  - title: About
    url: /about

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Asia/Kolkata
future:      true
highlighter: rouge
#markdown:    kramdown
paginate:    5
paginate_path: "page:num"
highlight_theme: light

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:year/:month/:categories/:title

prose:
  rooturl: '_posts'
  siteurl: 'https://saurabhshri.github.io'
  relativeLinks: 'https://saurabhshri.github.io/links.jsonp'
  media: 'images'
  metadata:
    _posts:
      - name: "published"
        field:
          label: "Published"
          element: "checkbox"
          value: "true"
      - name: "layout"
        field:
          element: "hidden"
          label: "Layout"
          value: "post"
      - name: "title"
        field:
          label: "Title"
          element: "text"
          value: "An Awesome Headline!"
      - name: "description"
        field:
          element: "text"
          label: "Description"
          placeholder: "Enter Post Description"
      - name: "headline"
        field:
          element: "text"
          label: "beadline"
          placeholder: "Enter Post Headline"
      - name: "modified"
        field:
          element: "text"
          label: "Has this page been modified?"
          placeholder: "YYYY-MM-DD"
      - name: "categories"
        field:
          element: "multiselect"
          label: "Add categories"
          placeholder: "Choose categories"
          value: personal
          options:
            - name: "Personal"
              value: personal
            - name: "gsoc-how"
              value: gsoc-how
            - name: "GSoC"
              value: GSoC
            - name: "News"
              value: News
          alterable: true
      - name: "tags"
        field:
          element: "text"
          label: "Tags"
          placeholder: "Enter tags, separated by spaces"
      - name: "imagefeature"
        field:
          element: "text"
          label: "Featured Image"
          placeholder: "somefile.jpg"
      - name: "mathjax"
        field:
          element: "checkbox"
          label: "MathJax"
          value: false
      - name: "featured"
        field:
          element: "checkbox"
          label: "Featured?"
          value: false
      - name: "comments"
        field:
          element: "checkbox"
          label: "Comments"
          value: false


include: [".htaccess"]
exclude: ["lib", "config.rb", "Gemfile", "Capfile", "Gemfile.lock", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
